# Generated by Django 3.2.6 on 2021-08-16 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20210813_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='person.person'),
        ),
    ]
